"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
type Post = { post_id: string; texto: string; categoria: string; criado_em: string; usuarios?: { nome: string | null; email: string | null }[] | null };
export default function CommunityPage() {
  const [posts, setPosts] = useState<Post[]>([]); const [text, setText] = useState(""); const [category, setCategory] = useState("geral"); const [filter, setFilter] = useState("todas"); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) { setLoading(false); return; } const { data } = await supabase.from("community_posts").select("post_id, texto, categoria, criado_em, usuarios(nome, email)").order("criado_em", { ascending: false }); setPosts((data as Post[]) || []); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const publish = async (event: FormEvent) => { event.preventDefault(); setMessage(""); if (!text.trim()) { setMessage("Escreva algo antes de publicar."); return; } const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) { setMessage("Faça login para publicar."); return; } const { data: user } = await supabase.from("usuarios").select("empresa_id").eq("usuario_id", session.user.id).maybeSingle(); if (!user?.empresa_id) { setMessage("Não foi possível identificar a empresa."); return; } const { error } = await supabase.from("community_posts").insert({ empresa_id: user.empresa_id, usuario_id: session.user.id, categoria: category, texto: text.trim() }); if (error) { setMessage("Execute a migration 13_community.sql para ativar as publicações."); return; } setText(""); setMessage("Publicado na comunidade."); await load(); };
  const visiblePosts = useMemo(() => filter === "todas" ? posts : posts.filter((post) => post.categoria === filter), [filter, posts]);
  return <div style={wrapper}><div style={{ marginBottom: "16px" }}><h1 style={title}>Community</h1><p style={subtitle}>Troque experiências entre creators e equipe</p></div><form onSubmit={publish} style={card}><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Compartilhe algo com a comunidade..." style={textareaStyle} /><div style={composerFooter}><select value={category} onChange={(e) => setCategory(e.target.value)} style={select}><option value="geral">Geral</option><option value="campanhas">Campanhas</option><option value="aprendizado">Aprendizado</option><option value="dicas">Dicas</option></select><button type="submit" style={publishButton}>Publicar</button></div>{message && <div style={messageStyle}>{message}</div>}</form><div style={filterBar}><span>Publicações</span><select value={filter} onChange={(e) => setFilter(e.target.value)} style={select}><option value="todas">Todas</option><option value="campanhas">Campanhas</option><option value="aprendizado">Aprendizado</option><option value="dicas">Dicas</option><option value="geral">Geral</option></select></div>{loading ? <div style={empty}>Carregando publicações...</div> : visiblePosts.length === 0 ? <div style={empty}>Ainda não há publicações nesta categoria.</div> : <div style={postList}>{visiblePosts.map((post) => <div key={post.post_id} style={card}><div style={postHeader}><div style={avatarBox}>👤</div><div style={{ flex: 1 }}><div style={nameStyle}>{post.usuarios?.[0]?.nome || post.usuarios?.[0]?.email || "Membro da equipe"}</div><div style={userStyle}>{post.categoria} · {new Date(post.criado_em).toLocaleString("pt-BR")}</div></div></div><div style={postText}>{post.texto}</div></div>)}</div>}</div>;
}
const wrapper = { maxWidth: "640px", margin: "0 auto" }; const title = { fontSize: "22px", fontWeight: 700, margin: 0 }; const subtitle = { fontSize: "12px", color: "#6b7280", marginTop: "4px" }; const card = { background: "white", border: "1px solid #e5e7eb", borderRadius: "10px", padding: "12px" }; const textareaStyle = { width: "100%", minHeight: "72px", resize: "none" as const, border: "1px solid #e5e7eb", borderRadius: "8px", padding: "10px 12px", fontSize: "12px", boxSizing: "border-box" as const }; const composerFooter = { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "10px" }; const select = { border: "1px solid #d1d5db", borderRadius: "7px", padding: "7px 9px", fontSize: "11px", background: "white" }; const publishButton = { background: "#14b8a6", color: "white", border: "none", borderRadius: "999px", padding: "6px 14px", fontSize: "11px", fontWeight: 600, cursor: "pointer" }; const messageStyle = { color: "#0f766e", fontSize: "11px", marginTop: "8px" }; const filterBar = { display: "flex", justifyContent: "space-between", alignItems: "center", margin: "14px 0 8px", fontSize: "12px", fontWeight: 600, color: "#374151" }; const postList = { display: "grid", gap: "10px" }; const empty = { ...card, textAlign: "center" as const, color: "#6b7280", fontSize: "13px", padding: "28px" }; const postHeader = { display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }; const avatarBox = { width: "24px", height: "24px", borderRadius: "999px", background: "#e2e8f0", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "12px" }; const nameStyle = { fontSize: "12px", fontWeight: 600, color: "#111827" }; const userStyle = { fontSize: "10px", color: "#6b7280" }; const postText = { fontSize: "12px", color: "#374151", lineHeight: 1.55, whiteSpace: "pre-wrap" as const };
